"""
Discriminator/value fn:
Given two sets of bitmaps (i.e., bitmaps sampled from current working program vs. input bitmaps),
return a scalar score judging how likely the sets are to be generated by the same program.
"""

